spring:
  application:
    name: stock-service

server:
  port: 8301


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://load-balancer:8761/eureka/
  instance:
    hostname: localhost